import { BrandOverrides } from "../get-brand-colors";

export const demoOverrides: BrandOverrides = {
  light: {
    background: "#f5faf7",
    backgroundSurface: "#edf7f2",
    foreground: "#1a2c20",
    card: "#ffffff",
    cardForeground: "#1a2c20",
    popover: "#ffffff",
    popoverForeground: "#1a2c20",
    primary: "#16a34a",
    primaryForeground: "#ffffff",
    primaryLight: "#22c55e",
    secondary: "#e6faea",
    secondaryForeground: "#1a2c20",
    muted: "#e6faea",
    mutedForeground: "#64748b",
    accent: "#bbfbd0",
    accentForeground: "#1a2c20",
    destructive: "#e53e3e",
    destructiveForeground: "#ffffff",
    border: "#cbefd6",
    input: "#cbefd6",
    ring: "#16a34a",
    warning: "#ed8936",
    warningForeground: "#fffbeb"
  },
  dark: {
    background: "#0f291a",
    backgroundSurface: "#1e3b2c",
    foreground: "#f8fcfa",
    card: "#1e3b2c",
    cardForeground: "#f8fcfa",
    popover: "#1e3b2c",
    popoverForeground: "#f8fcfa",
    primary: "#16a34a",
    primaryForeground: "#ffffff",
    primaryLight: "#22c55e",
    secondary: "#1e5a37",
    secondaryForeground: "#f8fcfa",
    muted: "#1e5a37",
    mutedForeground: "#94b8a3",
    accent: "#15803d",
    accentForeground: "#f8fcfa",
    destructive: "#7f1d1d",
    destructiveForeground: "#ffffff",
    border: "#237649",
    input: "#237649",
    ring: "#16a34a",
    warning: "#f59e0b",
    warningForeground: "#78350f"
  },
  chart: {
    "1": "#16a34a",
    "2": "#22c55e",
    "3": "#15803d",
    "4": "#166534",
    "5": "#4ade80"
  }
};